[env:attiny3216]
platform = atmelmegaavr
board = attiny3216
framework = arduino

board_build.f_cpu = 20000000L
board_fuses.osccfg = 0x02

# Hardcode the port here so PlatformIO always passes it correctly
upload_port = COM4

upload_protocol = custom

upload_command = pymcuprog write -t uart -u $UPLOAD_PORT -d $BOARD_MCU -i updi --erase --verify -c 115200 -f "$SOURCE"

extra_scripts = pre:increment_version.py

lib_deps =
    powerbroker2/SerialTransfer@^3.1.3